### ISSUE TITLE
[BUG] Imagem continua na lista de ficheiros depois do post ser feito

### ISSUE THREAD

**Issue by danoninho1234** [l29utp0/ptchina#16]
Quando um post é feito e a imagem não é enviada, a imagem continua na lista.

Este problema poderá estar relacioada com o commit [cb6f1cb0921788c743dc7b5a51ed244f08fc9115](https://github.com/l29utp0/ptchina/commit/cb6f1cb0921788c743dc7b5a51ed244f08fc9115)

**Comment by l29utp0** [comment]
Não consigo reproduzir, mais informações?

**Comment by l29utp0** [comment]
Ok já percebi o que é, é no Firefox quando não se tem nenhum especial selecionado.

**Comment by l29utp0** [comment]
Arranjado #17 
Se bem que talvez não da melhor forma
