### ISSUE TITLE
README.md próprio

### ISSUE THREAD

**Issue by Lacerkage** [l29utp0/ptchina#43]
Atualmente o README.md do repositório é o mesmo do fatchan.
Acredito que seria melhor ter um ficheiro README próprio para o ptchan, talvez mesmo até em português.

**Comment by l29utp0** [comment]
A documentação e comentários no código também está tudo em inglês. Como são coisas mais técnicas, instalação, manutenção, etc talvez seja melhor manter uniforme.
Mas não me oponho em ter um readme alternativo em português, README-pt.md por exemplo.

**Comment by loynet** [comment]
Penso que se for acrescentada uma frase ou duas a dizer (em inglês) que o repositório tem o código que corre no ptchan.org e, como tal, incluí algumas personalizações e está traduzido para português não se perde nada. 
Também acho que é melhor ideia deixar as instruções semelhantes ao fatchan até o fork divergir ao ponto de ter instruções diferentes.

**Comment by Lacerkage** [comment]
Algo que eu faria seria acrescentar screenshots do ptchan e não do fatchan
